# version: "3.8"

services:
  wg-easy:
    environment:
      # ⚠️ Public IPv4 Address or host name
      - WG_HOST=
      # ⚠️ Admin password
      - PASSWORD=
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    hostname: wg-easy
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

  app:
    container_name: app
    image: app
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    environment:
    # ⚠️ OpenWeather API KEY
      - API_KEY=